### ISSUE TITLE
Light propagation inside lenses or gratings

### ISSUE THREAD

**Issue by LiuX2018** [rafael-fuente/diffractsim#44]
Is there a method for modeling light propagation inside lenses or gratings? Specifically, we may treat them as thick components instead of simple transmission functions.

**Comment by rafael-fuente** [comment]
Hi. There is no currently implemented method for propagating light inside a lens. Generally, this would require a full wave simulation of the lens using a tool like meep FDTD, which is beyond this project's scope. (Although you can still implement in meep FDTD your simulated lens, store the field and load it with diffractsim to study the free-space propagation.

Another possibility is to look at approximate methods,  like BPM.

**Comment by LiuX2018** [comment]
Ok, thanks very much.
