### ISSUE TITLE
`interp2d` has been removed in SciPy 1.14.0.

### ISSUE THREAD

**Issue by a-photon-here** [rafael-fuente/diffractsim#52]
The screenshot of the error is attached below.
![Screenshot 2024-07-09 152847](https://github.com/rafael-fuente/diffractsim/assets/175133301/f5519841-5d1d-4094-b7b9-5ff710bf4492)

**Comment by rafael-fuente** [comment]
Hi, thanks for noticing it; I replaced the deprecated interpolation function in the new version of diffractsim
