### ISSUE TITLE
Issue with Scipy interp2d

### ISSUE THREAD

**Issue by angeAnonyme** [rafael-fuente/diffractsim#55]
With the latest version of Scipy, I ran into some error due to interp2d been depleated:

"NotImplementedError: `interp2d` has been removed in SciPy 1.14.0."

The solution was to change, it in the .util.image_handling.py, the resize_array function. Here is the new code:
```
def resize_array(img_array, new_shape):

    Ny, Nx = img_array.shape
    
    """from scipy.interpolate import interp2d
    fun = interp2d(
        np.linspace(0, 1, Nx),
        np.linspace(0, 1, Ny),
        img_array,
        kind="cubic",
    )
    resize_img_array = fun(np.linspace(0, 1, new_shape[1]), np.linspace(0, 1, new_shape[0]))
    """
    from scipy.interpolate import RectBivariateSpline
    r = RectBivariateSpline(np.linspace(0, 1, Nx), np.linspace(0, 1, Ny), img_array.T)

    rt = lambda xnew, ynew: r(xnew, ynew).T
    resize_img_array = rt(np.linspace(0, 1, new_shape[1]), np.linspace(0, 1, new_shape[0]))

    
    return resize_img_array
```

Solution inspired from: https://gist.github.com/ev-br/8544371b40f414b7eaf3fe6217209bff

**Comment by LtqxWYEG** [comment]
I just replaced the word `interp2d `with `RectBivariateSpline `and commented out `kind="cubic"`. works flawlessly, afaik and by what scipy told me in the error message.  
BTW, in your code example is the old not-working code

**Comment by angeAnonyme** [comment]
Awesome, thanks for the great work.
Indeed I had the old code but it was commented ("""..."""). It was for reference.
I am unsure why my solution was using the transpose function, but if it works without, it's easier. I close the issue.

**Comment by LtqxWYEG** [comment]
> Indeed I had the old code but it was commented ("""..."""). 

Oh! You know, you can use code highlighting by adding the language used after the first three ' here in github.

```python
Print("like for example...."+23+variable)
```
So, like '`''python`.
